services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  django:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/App
    command: ["daphne", "-b", "0.0.0.0", "-p", "8000", "base.asgi:application"]
    depends_on:
      - redis

  celery:
    build:
      context: .
      dockerfile: dockerfile
    command: ["celery", "-A", "base", "worker", "-l", "INFO"]
    volumes:
      - .:/App
    depends_on:
      - redis
      - django
