# Generated by Django 6.0 on 2025-12-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('rider', 'Rider'), ('driver', 'Driver'), ('Admin', 'admin')]),
        ),
    ]
