# Generated by Django 6.0 on 2025-12-06 07:31

import servers.auth_user.usermanager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0003_alter_customuser_email_alter_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', servers.auth_user.usermanager.customUserManager()),
            ],
        ),
    ]
