# Generated by Django 5.0.3 on 2026-02-16 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_doc', models.CharField(blank=True, max_length=512, null=True)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('off', 'Off'), ('active', 'Active'), ('on ride', 'On Ride'), ('off ride', 'Off Ride'), ('blocked', 'Blocked')], default='off', max_length=20)),
                ('total_trips', models.IntegerField(default=0)),
                ('ratings', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('car', 'Car'), ('auto', 'Auto')], max_length=10)),
                ('model', models.CharField(max_length=100)),
                ('reg_num', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
            ],
        ),
    ]
