# Generated by Django 5.0.3 on 2026-02-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_vehicletype_rename_reg_num_vehicle_vehicle_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicletype',
            old_name='name',
            new_name='type',
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
