# Generated by Django 5.0.3 on 2026-02-16 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_rename_name_vehicletype_type_vehicletype_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='driver.driver')),
            ],
        ),
    ]
