# Generated by Django 5.0.3 on 2026-02-16 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_driverearning'),
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverearning',
            name='trip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_earnings', to='ride.trip'),
        ),
    ]
