# Generated by Django 6.0 on 2025-12-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteLocations',
            new_name='FavoriteLocation',
        ),
    ]
