# Generated by Django 6.0 on 2025-12-06 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0002_rename_favoritelocations_favoritelocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelocation',
            name='rider_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritelocation', to='rider.rider'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider', to=settings.AUTH_USER_MODEL),
        ),
    ]
