# Generated by Django 6.0 on 2025-12-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0004_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
