# Generated by Django 6.0 on 2025-12-08 14:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0003_alter_driver_rating'),
        ('rider', '0006_emergencycontacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('src_lat', models.FloatField()),
                ('src_lng', models.FloatField()),
                ('dest_lat', models.FloatField()),
                ('dest_lng', models.FloatField()),
                ('is_shared', models.BooleanField()),
                ('estimated_amount', models.FloatField()),
                ('actual_amount', models.FloatField()),
                ('surge_mult', models.DecimalField(decimal_places=2, max_digits=3)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='driver', to='driver.driver')),
                ('rider_id', models.ManyToManyField(related_name='riders', to='rider.rider')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vehicle', to='driver.vehicle')),
            ],
        ),
    ]
